import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
    en: {
        signup: 'SignUp',
        login: 'Login',
        home: 'Home',
        jwttoken: 'jwttoken',
        createUser: 'Create User',
        logout: 'Logout',
        addTrips: 'Add Trips',
        findUsers: 'Find Users',
        role: 'role',
        register: 'Register',
        delete: 'Delete',
        edit: 'Edit',
        view: 'View',
        destination: 'Destination',
        startDate: 'Start Date',
        endDate: 'End Date',
        comment: 'Comment',
        somethingWentWrong: 'something went wrong',
        action: 'Action',
        id: 'id',
        editTrip: 'Edit Trip',
        editUser: 'Edit User',
        name: 'Name',
        email: 'email',
        back: 'Back to Home',
        loadMore: 'Load More',
        noData: 'No Data Available',
        userId: 'User Id',
        hash: '#',
        tripId: 'Trip Id:',
        addTrip: 'Add a Trip',
        addUser: 'Add a User',
        success: 'Success',
        tripSuccessfullyAdded: 'Trip Successfully Added',
        tripUpdated: 'Trip Updated',
        tripDeleted: 'Trip Deleted',
        userUpdated: 'User Updated',
        userDeleted: 'User Deleted',
        userSuccessfullyAdded: 'User Successfully Added',
        startMsg: 'Start date Max should be less than start Date Min',
        endMsg: 'End date Max should be less than End Date Min',
        count: 'Day Count',
        clearFilters: 'Clear Filters',
        search: 'Search',
        nextMonthPlan: 'Next Month Plan',
        ownTrips: 'Own Trips'

    }

})